### ISSUE TITLE
Плагиат спрайтов

### ISSUE THREAD

**Issue by SunkyMP3G** [Lehanchic25/Planet-Gebr#1]
### Объясняйся, а также удаляй все эти спрайты
(Сначала плагиат, затем оригинал)
Весь текст хранится у меня лично, при удалении верну всё
![image](https://github.com/Lehanchic25/Planet-Gebr/assets/125795960/0dfae2ab-950a-417a-85bf-6a96bfdd5551) 
![image](https://github.com/Lehanchic25/Planet-Gebr/assets/125795960/8b3b77fd-3d88-4894-b4ee-a4ee5cc9db98)
-----
![image](https://github.com/Lehanchic25/Planet-Gebr/assets/125795960/0b32d151-8306-4958-b213-1c0c61fb3a85)
![image](https://github.com/Lehanchic25/Planet-Gebr/assets/125795960/e416e4d8-24db-48eb-a217-71986a552963)
-----
![image](https://github.com/Lehanchic25/Planet-Gebr/assets/125795960/3a09e04c-1906-417c-8fb6-326b5624ab5e)
![image](https://github.com/Lehanchic25/Planet-Gebr/assets/125795960/34ca7ba6-b0ef-4451-848f-7d96944a5f84)
-----
![image](https://github.com/Lehanchic25/Planet-Gebr/assets/125795960/72e2c8a5-f7e6-471a-a69e-0d6111849f70)
![image](https://github.com/Lehanchic25/Planet-Gebr/assets/125795960/bd8f2904-2489-4eec-9625-d969a2397a0c)
(Нет скрина в игре из-за респрайта железа)

**Comment by Lehanchic25** [comment]
Привет! Я начинающий програмист, раньше делал мини проэкты по миндастри, это первый более менее глобальный мод. Я не очень умею создавать спрайты (т.к я програмист, работаю один над картами, кодом и всем другим), поэтому беру из других модов (или ванильной игры) и перерисовываю их, чтобы появились хоть какие то спрайты (потому что как то не очень смотрится предмет с текстурой oh no). Я тебя услышал, пока что не буду делать свой мод, буду делать нормальные спрайты. Насчёт железа, да я его спрайт тоже взял, но подумал что т.к это практически как медь выглядеть будет более менее нормально.

Надеюсь что ты меня поймёшь. Скоро я все спрайты переделаю (в том числе и в старом релизе).

**Comment by SunkyMP3G** [comment]
На пк есть Aseprite, лучшая программа для пиксель артов. Научиться будет немного сложно, но затем легко будет работать со спрайтами. За другими альтернативами можешь зайти на дс минды и посмотреть канал #spriting (на английском)

**Comment by Lehanchic25** [comment]
Ок, я понял. Эта программа у меня уже была установленнана мой пк, спасибо за помощь

**Comment by Lehanchic25** [comment]
Всё, все спрайты поправленны. И я научился лучше пользоваться этой программой (до этого я в ней рисовал другие спрайты)
![Зелье здоровья](https://github.com/Lehanchic25/Planet-Gebr/assets/136587212/90403715-6225-4eea-bf30-6fcd8974a9de)
![Жареное мясо](https://github.com/Lehanchic25/Planet-Gebr/assets/136587212/8d73ea9a-a021-4c37-bafd-75e028dea407)
![Сырое мясо](https://github.com/Lehanchic25/Planet-Gebr/assets/136587212/7555b794-ebb7-47b4-8d61-2a43dc0114c8)

**Comment by Lehanchic25** [comment]
И вопрос. Я ещё брал у тебя части кода (на сравнении первого спрайта видно), мне изменять параметры?

**Comment by SunkyMP3G** [comment]
На параметры мне всё равно, но желательно их настроить для баланса ~~_вселенной_~~.
Возможно стоит оформить код для своего удобства и определиться с hjson'ом и простым json'ом, не стоит иметь сразу два формата.

**Comment by SunkyMP3G** [comment]
И кстати, про саму планету, стоило бы сменить стиль облаков, стиль самой планеты вполне нормальный

**Comment by SunkyMP3G** [comment]
Новый радон кстати выглядит достаточно хорошо

**Comment by Lehanchic25** [comment]
Кстати, у меня к тебе вопрос, почему для перехода на другой сектор мне нужна медь и свинец? Как это пофиксить (уже с самого начала создания мода я так и не понял)

**Comment by SunkyMP3G** [comment]
Нужно создать схему в игре с необходимым ядром, затем перекинуть файл со схемой в папку schematics мода, и в секторах кроме самого первого поставить строку "loadout: "[имя файла схемы]""

**Comment by Lehanchic25** [comment]
Спасибо
