### ISSUE TITLE
 Ай.. какой ты не хороший

### ISSUE THREAD

**Issue by RouterXdd** [Lehanchic25/Planet-Gebr#2]
Зачем таки тырить спрайты из Аеамы?
![Снимок экрана 2023-12-31 221841](https://github.com/Lehanchic25/Planet-Gebr/assets/91018607/2662b011-116b-4e7c-8e14-ed09849c1e32)

**Comment by Lehanchic25** [comment]
Привет! Я могу сам создавать спрайты с помощью программы Aseprite. Но сейчас я не дома и чтобы было текстурка не ошибки я поставил текстурку из этого мода перерисовав некоторые спрайты. Я могу попробовать рисовать на телефоне. Но уверен что будет сейчас фигня.

Я скоро в 2024 году когда приеду домой  (я сейчас 800 км от дома) переделаю текстурки. Если ты скажешь: "Перерисовывай хоть на телефоне. Без разницы." Тогда хорошо я нарисую, но тогда мне это прийдётся снова перерисовывать и тогда замедлится развитие мода.

Выбор за тобой.

**Comment by Lehanchic25** [comment]
С новым годом тебя! (Закрытие я случайно нажал)

**Comment by SunkyMP3G** [comment]
Если что, можно использовать спрайты самой игры, или делать шаблоны, что-бы ими временно заменять пустые спрайты
