### ISSUE TITLE
Нельзя пройти "Восточные поля"

### ISSUE THREAD

**Issue by Arsen1yGD** [Lehanchic25/Planet-Gebr#3]
По сути я должен был захватить это на 30 волне, но уже 500 волна.
Понимаю что трабл ещё не доделан, но это вообще пипец
![20240129202337_1](https://github.com/Lehanchic25/Planet-Gebr/assets/147246788/ff9a2391-d97a-4c4e-89d8-dc6da9273d30)

**Comment by Lehanchic25** [comment]
Я понял, в карте всё нормально, поэтому скорее всего дело в коде сектора, сейчас попробую исправить

**Comment by Lehanchic25** [comment]
В коде не хватало лишь 1 строчки
