### ISSUE TITLE
Есть предложение, помощь с картами

### ISSUE THREAD

**Issue by Ochpochmaks** [Lehanchic25/Planet-Gebr#5]
Привет! Когда я проходил кампанию на Гебре я заметил что карты выглядят не очень и их мало, если хочешь я могу помочь тебе с картами, у меня уже есть карта для Гебра (если хочешь конечно добавить) я тебе отправлю. Могу сделать карты и для Тробла. Обдумай это предложение и напиши - помогать тебе или нет:)

**Comment by Lehanchic25** [comment]
Привет! Я готов сотрудничать, я не очень хорош в картах и юнитах. Так что если хочешь мы можем продолжать улучшать мод!

У меня ещё долгое время было выгорание к этому проекту, но сейчас я готов продолжать его дополнять.

**Comment by Lehanchic25** [comment]
Я также сделал новую ветку где мы начнём добавлять всё по немногу

**Comment by Lehanchic25** [comment]
Начнём туда добавлять, если что тестить будем вдвоём, если будет всё хорошо, я тогда сделаю реквест и перекину из этой ветки `Новые-карты` я всё перекину в обычную это будет в релизе

**Comment by Ochpochmaks** [comment]
Хорошо, у меня уже есть карта которую я доделал, но ты измени её под своё усмотрение и она не Гебр, извини за то что смотрю гитхаб мало:)

**Comment by Lehanchic25** [comment]
Отлично, тогда ты мне её можешь скинуть в дискорде (lehanchic25)

**Comment by Ochpochmaks** [comment]
Хорошо
